name: Rasmus Mikkelsen
description: Personal site and blog
meta_description: "Rasmus Mikkelsen personal blog"


markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://smus.nu/'
google_analytics: 'UA-627005-7'

gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives

# Details for the RSS feed generator
url:            ''
author:         'Rasmus Mikkelsen'

permalink: '/blog/:year/:month/:day/:title/'

jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: archive-layout-tag
