name: Rasmus Mikkelsen
description: Personal site and blog
meta_description: "Rasmus Mikkelsen personal blog"

markdown: kramdown
logo: false
paginate: 15
baseurl: /
domain_name: 'http://smus.nu/'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            ''
author:         'Rasmus Mikkelsen'
